backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "config"
    label: "Contenu du Site"
    files:
      - file: "content/home.json"
        label: "Page d'accueil"
        name: "home"
        fields:
          - {label: "Titre du Stage", name: "hero_title", widget: "string"}
          - {label: "Description", name: "hero_desc", widget: "text"}
          - {label: "Image Principale", name: "hero_img", widget: "image"}
          
          - label: "Avantages"
            name: "advantages"
            widget: "list"
            fields:
              - {label: "Icône", name: "icon", widget: "string"}
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Description", name: "desc", widget: "text"}
              
          - label: "Équipe"
            name: "team"
            widget: "list"
            fields:
              - {label: "Nom", name: "name", widget: "string"}
              - {label: "Poste", name: "role", widget: "string"}
              - {label: "Photo", name: "photo", widget: "image"}